# Generated by Django 2.0.7 on 2018-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_scrapper', '0002_exchangerate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
