# Generated by Django 2.0.7 on 2018-07-26 11:11

from django.db import migrations, models
import requests
from bs4 import BeautifulSoup

url_with_rss = 'https://www.ecb.europa.eu/home/html/rss.en.html'
exchanges_list_class = 'zebraList'


def add_exchange_rss(apps, schema_editor):
    MyModel = apps.get_model('exchange_scrapper', 'ExchangeRSS')
    try:
        for exchange_data in get_urls():
            MyModel.objects.create(name=exchange_data[1][-4:-1], slug=exchange_data[0])
    except:
        raise ('something went wrong')


def get_urls():
    urls = []
    response = requests.get(url_with_rss)
    html = BeautifulSoup(response.text, 'html.parser')
    for ul in html.find_all('ul', class_=exchanges_list_class):
        for li in ul.find_all('li'):
            a = li.find('a')
            url = a['href'], a.get_text()
            if url[0].startswith('/rss/fxref'):
                urls.append(url)
    return urls


class Migration(migrations.Migration):
    dependencies = [
        ('exchange_scrapper', '0003_auto_20180726_1111'),
    ]

    operations = [
        migrations.RunPython(add_exchange_rss),
    ]
