# Generated by Django 2.0.7 on 2018-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_scrapper', '0004_exchange_rss_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
